(()=>{
const c=document.querySelector('#scene'),x=c.getContext('2d'),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const asset=n=>{const i=new Image();i.src=`assets/${n}`;return i};
const kitchenImg=asset('kitchen-3d.webp'),prepImg=asset('prep-board.webp'),filletImg=asset('fillet-board.webp'),soyImg=asset('soy-bottle.webp'),potImg=asset('simmer-pot.webp'),plateImg=asset('ceramic-plate.webp'),cookedImg=asset('cooked-mackerel.webp');
let W=480,H=820,d=1,stage=0,phase='intro',progress=0,pointer=false,draggingFish=false,last={x:0,y:0},particles=[],bones=[],pour=0,fire=.2,goodHeat=0,plateFish={x:185,y:430},startTime=Date.now(),raf=0,lastFrame=performance.now();
const titles=['うろこを取ろう！','小骨を抜こう！','煮汁をつくろう！','焦がさず煮付けよう！','崩さず盛り付け！'];
const subs=['魚を左右にゴシゴシ','光っている骨をすべてタップ','醤油を適量まで注いで止める','つまみを動かして緑をキープ','魚をお皿までゆっくり運ぶ'];
const hints=['左右にスワイプ','骨をタップ','長押しで注ぐ','火加減をスライド','お皿へドラッグ'];
const familyLines=['今日のお魚、楽しみ！','骨が残ってないかな？','いい匂いしてきた！','おなかすいた〜！','わあ、おいしそう！'];
function resize(){const r=c.getBoundingClientRect();d=Math.min(2,devicePixelRatio||1);c.width=r.width*d;c.height=r.height*d;W=r.width;H=r.height;x.setTransform(d,0,0,d,0,0)}addEventListener('resize',resize);resize();
function sx(v){return v*W/480}function sy(v){return v*H/820}function path(p,fill,stroke){x.beginPath();x.moveTo(sx(p[0][0]),sy(p[0][1]));for(let i=1;i<p.length;i++)x.lineTo(sx(p[i][0]),sy(p[i][1]));x.closePath();x.fillStyle=fill;x.fill();if(stroke){x.strokeStyle=stroke;x.lineWidth=2;x.stroke()}}
function ell(a,b,rx,ry,fill){x.beginPath();x.ellipse(sx(a),sy(b),sx(rx),sy(ry),0,0,Math.PI*2);x.fillStyle=fill;x.fill()}function rect(a,b,w,h,r,fill){x.beginPath();x.roundRect(sx(a),sy(b),sx(w),sy(h),sx(r));x.fillStyle=fill;x.fill()}function txt(t,a,b,s,col='#fff',font='900'){x.font=`${font} ${Math.max(14,sx(s))}px "Yu Gothic",sans-serif`;x.textAlign='center';x.textBaseline='middle';x.fillStyle=col;x.fillText(t,sx(a),sy(b))}
function iso(a,b,w,h,z,top,side,front){path([[a-w/2,b],[a,b-h/2],[a+w/2,b],[a,b+h/2]],top);path([[a-w/2,b],[a,b+h/2],[a,b+h/2+z],[a-w/2,b+z]],side);path([[a+w/2,b],[a,b+h/2],[a,b+h/2+z],[a+w/2,b+z]],front)}
function room(){
 if(kitchenImg.complete&&kitchenImg.naturalWidth){x.drawImage(kitchenImg,0,0,W,H)}else{x.fillStyle='#d7e9eb';x.fillRect(0,0,W,H)}
 const shade=x.createLinearGradient(0,0,0,H);shade.addColorStop(0,'#123f5a18');shade.addColorStop(.45,'#0000');shade.addColorStop(1,'#2d160b35');x.fillStyle=shade;x.fillRect(0,0,W,H);
}
function art(img,cx,cy,w,h,rot=0){if(!img.complete||!img.naturalWidth)return;x.save();x.translate(sx(cx),sy(cy));x.rotate(rot);x.shadowColor='#071e2b72';x.shadowBlur=sx(18);x.shadowOffsetY=sy(10);x.drawImage(img,-sx(w/2),-sy(h/2),sx(w),sy(h));x.restore()}
function ellRaw(a,b,rx,ry,fill){x.beginPath();x.ellipse(a,b,rx,ry,0,0,Math.PI*2);x.fillStyle=fill;x.fill()}function pathRaw(p,fill){x.beginPath();x.moveTo(p[0][0],p[0][1]);for(let i=1;i<p.length;i++)x.lineTo(p[i][0],p[i][1]);x.closePath();x.fillStyle=fill;x.fill()}
function drawStage(){
 x.save();const zoom=1+Math.max(0,.08-Math.min(.08,(performance.now()%999999)/999999));x.translate(W/2,H/2);x.scale(zoom,zoom);x.translate(-W/2,-H/2);room();
 if(stage===0){art(prepImg,240,438,390,260);const n=18-Math.floor(progress);for(let i=0;i<n;i++){const a=i*.9;txt('✦',240+Math.cos(a)*95,425+Math.sin(a*1.7)*42,17,'#fff5c2')}taskBadge('うろこ取り',progress/18)}
 if(stage===1){art(filletImg,240,438,400,267);bones.forEach(b=>{if(!b.done){const p=4+Math.sin(performance.now()/130+b.x)*3;x.fillStyle='#a92e2b';x.strokeStyle='#fff';x.lineWidth=3;x.beginPath();x.arc(sx(b.x),sy(b.y),sx(8),0,Math.PI*2);x.fill();x.stroke();x.strokeStyle='#fff9';x.lineWidth=2;x.beginPath();x.arc(sx(b.x),sy(b.y),sx(15+p),0,Math.PI*2);x.stroke()}});taskBadge(`小骨 あと${bones.filter(b=>!b.done).length}本`,bones.filter(b=>b.done).length/Math.max(1,bones.length),false)}
 if(stage===2){art(potImg,230,455,335,224);art(soyImg,335,355,86,135,-1.08);if(pointer){const g=x.createLinearGradient(sx(282),sy(386),sx(267),sy(458));g.addColorStop(0,'#d1893a');g.addColorStop(1,'#542313');rect(277,385,8,73*pour,4,g)}meter('味の濃さ',pour,.52,.7)}
 if(stage===3){art(potImg,240,448,365,244);for(let i=0;i<5;i++){x.globalAlpha=.42+.22*Math.sin(performance.now()/280+i);txt('〜',190+i*25,346-Math.sin(performance.now()/250+i)*12,29,'#fff');x.globalAlpha=1}fireMeter()}
 if(stage===4){const pulse=8+Math.sin(performance.now()/180)*5;x.strokeStyle='#ffe39b';x.lineWidth=3;x.beginPath();x.ellipse(sx(332),sy(456),sx(92+pulse),sy(48+pulse/2),0,0,Math.PI*2);x.stroke();art(plateImg,332,456,205,128);art(cookedImg,plateFish.x,plateFish.y,170,112);txt('ここへ',332,530,13,'#fff')}
 x.restore();particles.forEach(p=>{ell(p.x,p.y,p.r,p.r,p.col);p.x+=p.vx;p.y+=p.vy;p.vy+=.08;p.life--});particles=particles.filter(p=>p.life>0)
}
function taskBadge(label,val,showPct=true){rect(145,537,190,34,17,'#fffdf4ef');rect(155,558,170,5,3,'#d8d2c5');rect(155,558,170*Math.max(0,Math.min(1,val)),5,3,'#a92e2b');txt(showPct?`${label} ${Math.round(Math.max(0,Math.min(1,val))*100)}%`:label,240,550,12,'#123f5a')}
function meter(label,val,lo,hi){rect(91,566,298,35,17,'#fff');const colors=['#5d91af','#e5b94e','#a92e2b'];rect(110,580,260,9,5,'#d8dfdc');rect(110,580,260*val,9,5,val<lo?colors[0]:val<=hi?colors[1]:colors[2]);rect(110+260*lo,574,260*(hi-lo),21,8,'#0000');x.strokeStyle='#244b5e';x.lineWidth=2;x.stroke();txt(label,240,558,11,'#123f5a')}
function fireMeter(){rect(89,565,302,55,18,'#fff');const g=x.createLinearGradient(sx(111),0,sx(369),0);g.addColorStop(0,'#6daed0');g.addColorStop(.38,'#e4bd51');g.addColorStop(.64,'#e4bd51');g.addColorStop(1,'#c54135');x.fillStyle=g;rect(110,584,260,13,7,g);const k=110+260*fire;ell(k,590,15,15,'#fff');x.strokeStyle='#123f5a';x.lineWidth=3;x.stroke();txt('弱火',113,609,10,'#4a6f82');txt('ちょうど',240,609,10,'#80601b');txt('強火',367,609,10,'#94302b');txt(`ちょうどをキープ ${Math.min(100,Math.round(goodHeat/3.2*100))}%`,240,555,13,'#123f5a')}
function sparks(cx,cy,n=16){for(let i=0;i<n;i++){const a=Math.PI*2*i/n;particles.push({x:cx,y:cy,vx:Math.cos(a)*(1+Math.random()*3),vy:Math.sin(a)*(1+Math.random()*3)-1,r:2+Math.random()*3,col:['#fff','#c99a45','#a92e2b','#5a9fb5'][i%4],life:35})}}
function pos(e){const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*480/r.width,y:(e.clientY-r.top)*820/r.height}}
function inBox(p,l,t,r,b){return p.x>=l&&p.x<=r&&p.y>=t&&p.y<=b}
function start(e){if(phase!=='play')return;last=pos(e);if(stage===0&&!inBox(last,65,340,415,525)){toast('魚の上をこすろう！');return}if(stage===3&&!inBox(last,85,540,395,635)){toast('下のつまみを動かそう！');return}if(stage===4){draggingFish=Math.hypot(last.x-plateFish.x,last.y-plateFish.y)<92;if(!draggingFish){toast('魚をつかんで運ぼう！');return}}pointer=true;c.setPointerCapture(e.pointerId);$('#hand').style.opacity=0;if(stage===2)pouring()}
function move(e){if(!pointer||phase!=='play')return;const p=pos(e),dx=p.x-last.x;if(stage===0&&inBox(p,65,340,415,525)&&Math.abs(dx)>4){progress+=Math.min(1.25,Math.abs(dx)/18);sparks(p.x,p.y,2);last=p;if(progress>=18)complete('うろこ取り完了！')}else if(stage===3){fire=Math.max(0,Math.min(1,(p.x-110)/260));last=p}else if(stage===4&&draggingFish){plateFish.x=Math.max(82,Math.min(398,p.x));plateFish.y=Math.max(350,Math.min(530,p.y));last=p}}
function end(e){if(!pointer)return;pointer=false;draggingFish=false;try{c.releasePointerCapture(e.pointerId)}catch(_){}if(stage===2){if(pour>=.52&&pour<=.7)complete('ちょうどいい味！');else{toast(pour>.7?'濃すぎた…ゆっくり注ごう':'もう少し注いで！');pour=0}}else if(stage===4){if(Math.hypot(plateFish.x-332,plateFish.y-456)<58)complete('きれいに盛れた！');else{toast('もう少しお皿の中央へ！');plateFish={x:185,y:430}}}}
function tap(e){if(stage!==1||phase!=='play')return;const p=pos(e);let hit=false;bones.forEach(b=>{if(!b.done&&Math.hypot(p.x-b.x,p.y-b.y)<30){b.done=true;hit=true;sparks(b.x,b.y,8)}});if(hit&&bones.every(b=>b.done))complete('小骨もすっきり！')}
function pouring(){const id=setInterval(()=>{if(!pointer||stage!==2){clearInterval(id);return}pour=Math.min(1,pour+.012)},40)}
function toast(t){$('#toast').textContent=t;$('#toast').classList.remove('show');void $('#toast').offsetWidth;$('#toast').classList.add('show');beep(540)}
function complete(msg){if(phase!=='play')return;phase='transition';toast(msg);sparks(stage===4?332:240,440,28);beep(720);if(navigator.vibrate)navigator.vibrate(25);if(stage<4){$('#transitionText').textContent=`次は「${titles[stage+1].replace('！','')}」`;setTimeout(()=>$('#transition').classList.add('show'),620);setTimeout(()=>$('#transition').classList.remove('show'),1220)}setTimeout(()=>{stage++;progress=0;pour=0;goodHeat=0;fire=.2;plateFish={x:185,y:430};if(stage>=5){showTable();return}setupStage();phase='play'},1320)}
function setupStage(){const pct=stage/4*82;$('#progressBar').style.width=pct+'%';$$('.progress li').forEach((e,i)=>{e.classList.toggle('done',i<stage);e.classList.toggle('on',i===stage)});$('#stepLabel').textContent=`STEP ${stage+1}`;$('#title').textContent=titles[stage];$('#sub').textContent=subs[stage];$('#hand b').textContent=hints[stage];$('#hand').classList.remove('cue');void $('#hand').offsetWidth;$('#hand').classList.add('cue');$('#hand').style.opacity=1;$('#hand').style.animationName=stage===0?'scrub':'none';$('#familyText').textContent=familyLines[stage];if(stage===1)bones=[{x:181,y:428},{x:221,y:448},{x:260,y:414},{x:299,y:435}]}
function showTable(){phase='reveal';$('#progressBar').style.width='100%';$('#prompt').style.opacity=0;$('#family').style.opacity=0;$('#hand').style.opacity=0;$('#tableReveal').classList.add('show');$('#tableReveal').setAttribute('aria-hidden','false');setTimeout(showEnd,2300)}
function showEnd(){phase='end';$('#tableReveal').classList.remove('show');$('#tableReveal').setAttribute('aria-hidden','true');$('#endcard').classList.add('show');$('#endcard').setAttribute('aria-hidden','false');if(window.gameEnd)window.gameEnd()}
function beep(f){try{const ac=beep.ac||(beep.ac=new AudioContext),o=ac.createOscillator(),g=ac.createGain();o.frequency.value=f;g.gain.setValueAtTime(.05,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+.16);o.connect(g).connect(ac.destination);o.start();o.stop(ac.currentTime+.16)}catch(_){}}
c.addEventListener('pointerdown',e=>{start(e);tap(e);if(window.gameStart)window.gameStart()});c.addEventListener('pointermove',move);c.addEventListener('pointerup',end);c.addEventListener('pointercancel',end);
$('#retry').addEventListener('click',()=>{stage=0;phase='play';progress=pour=goodHeat=0;fire=.2;plateFish={x:185,y:430};$('#prompt').style.opacity=1;$('#family').style.opacity=1;$('#endcard').classList.remove('show');$('#endcard').setAttribute('aria-hidden','true');$('#tableReveal').classList.remove('show');startTime=Date.now();setupStage()});
$('#cta').addEventListener('click',e=>{if(window.mraid&&window.mraid.open){e.preventDefault();window.mraid.open(e.currentTarget.href)}});
function begin(){startTime=Date.now();$('#startscreen').classList.add('leave');setTimeout(()=>{$('#startscreen').remove();phase='play';$('#hand').classList.add('cue')},520)}
function loop(t){const dt=Math.min(.05,(t-lastFrame)/1000);lastFrame=t;if(stage===3&&phase==='play'){if(fire>=.38&&fire<=.64)goodHeat+=dt;else goodHeat=Math.max(0,goodHeat-dt*.5);if(goodHeat>=3.2)complete('ふっくら煮えた！')}const mins=Math.min(35,Math.floor((Date.now()-startTime)/5000));$('#clock').textContent=`18:${String(24+mins).padStart(2,'0')}`;x.clearRect(0,0,W,H);drawStage();raf=requestAnimationFrame(loop)}setupStage();setTimeout(begin,2300);raf=requestAnimationFrame(loop);
})();
